### ISSUE TITLE
2023: The Final Season 完結篇 前篇

### ISSUE THREAD

**Issue by HuskyHsu** [zoeGuava/make-exercise-a-habit#1]
徵求梗圖

**Comment by alphatero** [comment]
![image](https://user-images.githubusercontent.com/46735230/153567502-17eb4395-dd28-414c-8cc0-a32b2ac64f44.png)

**Comment by ChiShouWu** [comment]
前輩 加油啊！

**Comment by zoeGuava** [comment]
乾 你怎麼也...
要了啦！！！

**Comment by KimberlyYen** [comment]
朝聖！前輩！坐

**Comment by LonelyYeezhiChicken** [comment]
來追隨前輩英明的腳步

**Comment by haha861924** [comment]
神串留名

**Comment by zoeGuava** [comment]
😨

**Comment by alphatero** [comment]
這週前輩更新沒
沒

**Comment by zoeGuava** [comment]
還沒....今天的 js30 也窗了...

**Comment by HuskyHsu** [comment]
用鼓勵代替責備
前輩一定是在忙其他事情沒有在看動畫！！！
優秀！！ 100分！！

**Comment by HuskyHsu** [comment]
# 一週又平安的過去了，感謝飛天小女警的努力！
![](https://shoplineimg.com/5ab875018d1db9e3db00025b/5d4f651d221454003ef71e71/1000x.jpg)

**Comment by ezcomenezgo** [comment]
朝聖推！前輩，加油啊！

**Comment by LonelyYeezhiChicken** [comment]
一人一留言;救救鉛筆額

**Comment by HuskyHsu** [comment]
![圖片 1](https://user-images.githubusercontent.com/18141436/158114913-222026b9-9b87-4916-acc6-af1cc83ace71.png)

大家的鼓勵一定還不夠！！！

**Comment by alphatero** [comment]
媽！我在這！
今天的前輩依舊的給力呢！

**Comment by beareatapple** [comment]
前輩加油啊！！！我迫不及待想看結局了！

**Comment by lee926427** [comment]
![IMG_1298](https://user-images.githubusercontent.com/40841221/158119421-6f311875-3a02-4545-a8e6-469c298211a9.jpg)

**Comment by HuskyHsu** [comment]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/18141436/159194026-b3168655-c4b8-4f8b-aa13-1291cb119a92.png">

早上好鉛筆
现在我有冰淇淋
我很喜欢冰淇淋
但是
巨人与人夫
比冰淇淋
巨人与人夫
巨人与人夫9
我最喜欢
所以…现在是音乐时间
准备 1 2 3
两个礼拜以后
巨人与人夫 ×3
不要忘记
不要错过
记得去电影院看巨人与人夫
因为非常好电影
动作非常好
差不多一样冰淇淋
再见

**Comment by ChiShouWu** [comment]
趙喜那又在學中文喔

**Comment by zoeGuava** [comment]
...................................................................
乾...不是，還剩兩集漫畫的進度 R

**Comment by LonelyYeezhiChicken** [comment]
> 趙喜那又在學中文喔

趙喜娜講中文超強，不過照片我只有看到一根冰淇淋啊?!

**Comment by ezcomenezgo** [comment]
這裡發生什麼事了 XDDDDDD

**Comment by haha861924** [comment]
![image](https://user-images.githubusercontent.com/40877568/159304689-b7ea26a0-5aad-4861-bdba-658f378edcd6.png)

**Comment by HuskyHsu** [comment]
![image](https://user-images.githubusercontent.com/18141436/159924675-a312f0c4-2094-4089-97b6-c1da8a632694.png)

我只是想備份梗圖，大家幫我按表情符號就可以

**Comment by HuskyHsu** [comment]
![image](https://user-images.githubusercontent.com/18141436/160567942-b8efa420-3125-4374-a5c8-e13275eb298d.png)

妳說妳　想要人夫　偏偏注定要落腳
情滅了　愛熄了　剩下妹子要不要

**Comment by LonelyYeezhiChicken** [comment]
![1607698040769](https://user-images.githubusercontent.com/61058224/162369229-d4ced0c4-b91d-483e-be37-7578d254ad01.jpg)


跪求鉛筆更新

**Comment by HuskyHsu** [comment]
艾連為了堅持理想，聯手哥哥吉克葉卡引發災難「地鳴」，解放了三道牆裡的數十萬名「城牆巨人」，向世界進行毀滅攻擊，這血染大地的濫殺之舉，讓眾人產生疑惑，原本只是為了「救人」善意，卻演變成「為了救人而殺人」，徹底失去初衷。

米卡莎、阿爾敏、萊納、馬可、里維、漢吉等人為了阻止艾連，聯手修復世上唯一的飛船，眼看速度跟不上巨人腳程，漢吉最後決定「帥一波」，將團長職位交接給阿爾敏，兵長里維亦尊重漢吉的決定，道別前對她講出經典台詞「獻出心臟吧」；但漢吉1人無法對抗數十萬名「城牆巨人」，最終於空中燃燒犧牲；死後的漢吉，到了天堂跟此前在戰役中犧牲的兵團會合，偉大的付出令觀眾鼻酸。

兩派人馬的比拚讓人看不下去，但過程也發生可愛環節！「女巨人」亞妮終於發現阿爾敏的真心，但亞妮想到現在不少人正在被巨人踩死，她卻在此跟阿爾敏談情說愛，決定為愛休戰，不跟阿爾敏踏上飛船抗戰；米卡莎原本不理解亞妮作為，但在看著亞妮望著阿爾敏，亞妮更說出「我想安穩地度過」，便理解對方心情。

《[進擊的巨人 The Final Season完結篇-前篇](https://tw.tv.yahoo.com/attack-on-titan_s4)》完整劇情可至Hami Video、MyVideo、friDay影音、KKTV、LINE TV、愛奇藝國際站、BILIBILI、Netflix收看。「後篇」最終大結局預定秋季上線。

**Comment by HuskyHsu** [comment]
![image](https://github.com/zoeGuava/Life-habits/assets/18141436/f162755c-7d66-45fd-ab29-d49f3787a0aa)

**Comment by zoeGuava** [comment]
QQQQ
2023.11.04

**Comment by HuskyHsu** [comment]
![image](https://github.com/zoeGuava/Life-habits/assets/18141436/2d0d4df4-6e44-45b4-b717-005aecf280fc)
